# Generated by Django 5.2.6 on 2025-09-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='User who acknowledged the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='environmentalimpactmetrics',
            index=models.Index(fields=['date'], name='analytics_e_date_c676c1_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalimpactmetrics',
            index=models.Index(fields=['-date'], name='analytics_e_date_665fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmetrics',
            index=models.Index(fields=['date'], name='analytics_p_date_82cc92_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmetrics',
            index=models.Index(fields=['-date'], name='analytics_p_date_87f269_idx'),
        ),
        migrations.AddIndex(
            model_name='systemperformancemetrics',
            index=models.Index(fields=['timestamp'], name='analytics_s_timesta_b50180_idx'),
        ),
        migrations.AddIndex(
            model_name='systemperformancemetrics',
            index=models.Index(fields=['-timestamp'], name='analytics_s_timesta_3a7dcb_idx'),
        ),
        migrations.AddField(
            model_name='userengagementmetrics',
            name='user',
            field=models.ForeignKey(help_text='User for engagement tracking', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dashboardalert',
            index=models.Index(fields=['is_active', 'alert_type'], name='analytics_d_is_acti_30b4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardalert',
            index=models.Index(fields=['category', 'is_active'], name='analytics_d_categor_e763e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardalert',
            index=models.Index(fields=['-created_at'], name='analytics_d_created_0b67b3_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['user', 'date'], name='analytics_u_user_id_2064f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['date'], name='analytics_u_date_aa1b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetrics',
            index=models.Index(fields=['-date'], name='analytics_u_date_8f3c1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userengagementmetrics',
            unique_together={('user', 'date')},
        ),
    ]
