# Generated by Django 5.2.6 on 2025-09-18 13:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('glass', 'Glass'), ('organic', 'Organic'), ('electronic', 'Electronic'), ('textile', 'Textile'), ('hazardous', 'Hazardous'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('credit_rate_per_kg', models.DecimalField(decimal_places=2, help_text='Credits earned per kilogram of this waste type', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('co2_reduction_per_kg', models.DecimalField(decimal_places=4, help_text='CO2 reduction in kg per kilogram of waste collected', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waste Category',
                'verbose_name_plural': 'Waste Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('community_cleanup', 'Community Cleanup'), ('school_program', 'School Program'), ('beach_cleanup', 'Beach Cleanup'), ('market_cleanup', 'Market Cleanup'), ('special_drive', 'Special Drive')], max_length=20)),
                ('location', models.TextField()),
                ('county', models.CharField(default='Kisumu', max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (leave blank for unlimited)', null=True)),
                ('bonus_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Credit multiplier for this event (e.g., 1.5 for 50% bonus)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('total_weight_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total weight collected during this event', max_digits=10)),
                ('total_credits_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits awarded for this event', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection Event',
                'verbose_name_plural': 'Collection Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('weight_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weight collected by this participant', max_digits=8)),
                ('credits_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credits earned by this participant in this event', max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_collection.collectionevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Participation',
                'verbose_name_plural': 'Event Participations',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='participants',
            field=models.ManyToManyField(related_name='participated_events', through='waste_collection.EventParticipation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('point_type', models.CharField(choices=[('drop_off', 'Drop-off Point'), ('collection', 'Collection Point'), ('recycling_center', 'Recycling Center'), ('community_center', 'Community Center')], max_length=20)),
                ('address', models.TextField()),
                ('county', models.CharField(default='Kisumu', max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('operating_hours', models.TextField(blank=True, help_text='Operating hours description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_categories', models.ManyToManyField(help_text='Types of waste accepted at this point', related_name='collection_points', to='waste_collection.wastecategory')),
            ],
            options={
                'verbose_name': 'Collection Point',
                'verbose_name_plural': 'Collection Points',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='collectionevent',
            name='target_categories',
            field=models.ManyToManyField(help_text='Types of waste targeted for this event', related_name='target_events', to='waste_collection.wastecategory'),
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_weight_kg', models.DecimalField(decimal_places=2, help_text='Estimated weight in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('location_description', models.TextField()),
                ('county', models.CharField(default='Kisumu', max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the waste', null=True, upload_to='waste_reports/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('collected', 'Collected'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Actual weight collected in kilograms', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='waste_collection.wastecategory')),
                ('collected_by', models.ForeignKey(blank=True, help_text='Person who collected this waste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_reports', to=settings.AUTH_USER_MODEL)),
                ('collection_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='waste_collection.collectionpoint')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Staff member who verified this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Report',
                'verbose_name_plural': 'Waste Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned', 'Credits Earned'), ('spent', 'Credits Spent'), ('bonus', 'Bonus Credits'), ('penalty', 'Penalty'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Credit amount (positive for earned/bonus, negative for spent/penalty)', max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('reference_id', models.CharField(blank=True, help_text='External reference ID (e.g., purchase order)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff member who processed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('waste_report', models.ForeignKey(blank=True, help_text='Related waste report if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='waste_collection.wastereport')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
