# Generated by Django 5.2.6 on 2025-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="User's current credit balance", max_digits=10),
        ),
    ]
