# Generated by Django 5.2.6 on 2025-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('youth', 'Youth'), ('sme', 'SME'), ('admin', 'Admin')], default='youth', help_text='User type', max_length=20),
        ),
    ]
