# Generated by Django 5.2.6 on 2025-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('youth', 'Youth')], default='youth', help_text='User type', max_length=20),
        ),
    ]
